apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: fractal-agents
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:DtNOEu17EEw4GpMVcjk=,iv:azNQMVl6T7ZiIoU0fOYtPu0/i1AuKBFxs/wxKRK2c1U=,tag:FW+p3b+WRIt1sJfcjnbQ4Q==,type:str]
sops:
    age:
        - recipient: age1d8mxyz340rdexgn068097s0le3tmf3898xd5a4qpqng4zdtg8sgswnx9r9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWFJuUGY0WS81MGhqeVls
            Q0hBcFFHMnNHdzlsVHZjOE9TZFp5NWNhV21nClovY0k4eHZXbEV6Yk8zeVFqbWJP
            MVR6RVcwdlFzU3VxVkN5czBEcVhpK0kKLS0tIHh6QmhwUVZDUGRPck9RUzB4Wmhy
            a2xGTHQ4amVWa3IwcXpORnpYZjdhdjgK94LxZO2PeV/7rQcV2t8LH7n3uRr7gvQT
            Vmf8DhItf+Nlqp3QaoZroR/L2olOB7cCbmB15Hi5plPL4lFotR/Zfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T02:39:14Z"
    mac: ENC[AES256_GCM,data:CHF39PULOcmlwpGl0eEStFyDKRx5pGJM2Ze90M4IzwCnKBukm7Vm8+KP8QhATCajy3OmpDA5eetx2I7RtqZR9VhREx/wsd3XbNItGZR0lQSoj7cCNKMyr7pdcqG1KTpcgU2dKq3zjPKio3W39o3WyaygMeRkMVn5SA4Lv5MOFQY=,iv:r2JTf1ZXKYpvYDPMJ1xVOCZ7k8iTF6FNtLSgCYyEzFY=,tag:CQ+esNZ3tvdHiLmNYyLpxw==,type:str]
    encrypted_regex: ^(data|stringData|token|.*_TOKEN|.*_PASSWORD|.*_KEY)$
    version: 3.11.0
