apiVersion: v1
kind: Secret
metadata:
    name: fractal-secrets
    namespace: ai
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:YON6eaKjjoaUtf3K52U=,iv:md0nU5LLQi5hLKYgG+KoK5tPFZiCmEURMPnjDOEkvbY=,tag:KDXsHxF7EflCr9gsMrKH3A==,type:str]
    QDRANT_API_KEY: ENC[AES256_GCM,data:6dmfYmPIZZKqHy0=,iv:aZy9cjiN0Yar05f6qgGybF+CaMfju0LQvw1qV/NzNSo=,tag:apCGesOQG9QyuP6RfHhDIQ==,type:str]
sops:
    age:
        - recipient: age1d8mxyz340rdexgn068097s0le3tmf3898xd5a4qpqng4zdtg8sgswnx9r9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSjlJcTVlQWw3MGtzMEQy
            bG1mNG9sbGpOaDRHNU1Ma2w1MWd6ZGQ2bDAwCkJhTU1WMVlKc2xCd0lWc0U2MHBj
            MjYrUFJoM2dVZzVSbFlWQkZkL0pCMHMKLS0tIFB6WmtsbVJSdE9HTG9sZ2dTSGl3
            V0x6MVdZSElETjNLb0V6VWNTTHlvVW8K8AcY2Lzze3daC76wddNA9vjmi7wJjeRm
            bHOPuAcIrnZobdPTbPdZ0VBIeRDNzHwQIe4xWcC1pORq9rF7pJmMwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T02:41:59Z"
    mac: ENC[AES256_GCM,data:weeS8EmnWCR9T7NdjrmcIQrlMGD44Qd+Fok8rSbRJYksjg9yeZMYeJ5gNvP2HnwBsNyNnLixruvaJ23k/KiCV/BLMfuip3Ymm1DlZHy/fUz2nI9p0Zjvn6xd0xoPje+2vmGaztFdv/gTNplOULHkEScPmw27DG33Kq9/rYkn6+k=,iv:24+gZnpc33xDDY18T4UpVBnIBQsfdwAI7QUHPSQvKjA=,tag:KZordOZu6l2grHnEEOTNTw==,type:str]
    encrypted_regex: ^(data|stringData|token|.*_TOKEN|.*_PASSWORD|.*_KEY)$
    version: 3.11.0
